### ISSUE TITLE
Expected a JavaScript module script but the server responded with a MIME type of "text/plain".

### ISSUE THREAD

**Issue by tengfong00** [evan-buss/openbooks#47]
The command I use it just normal `openbooks server`
![image](https://user-images.githubusercontent.com/56729463/147469716-f4dabe53-f53d-43ad-a56a-10c052e52648.png)
![image](https://user-images.githubusercontent.com/56729463/147469723-60638647-2a4c-49e8-882b-30c00b02ab35.png)

This is what the browser devtools console error came out with a blank white screen.
![image](https://user-images.githubusercontent.com/56729463/147469515-d91e56a7-afd3-4580-b3f9-9e4ae6aaa10d.png)

**Comment by evan-buss** [comment]
I encountered this issue on Windows 11. Are you using Windows by chance? I see [this issue](https://github.com/golang/go/issues/32350) in the Go repository. It seems this is caused by incorrect configuration in the Windows Registry. Some applications (such as Visual Studio) modify the registry. See [Stack Overflow](https://stackoverflow.com/questions/12003107/resource-interpreted-as-script-but-transferred-with-mime-type-text-plain-for-l).

I was able to fix this on my machine by modifying the registry seen below.

Before:
![image](https://user-images.githubusercontent.com/18509589/147490640-7ea27496-2c0e-4846-a8c3-a28fab9914b7.png)

After:
![image](https://user-images.githubusercontent.com/18509589/147490846-1e4ec190-2bf0-4475-87a7-b18f3b77f6b4.png)

After updating the "Content Type" entry. The web page loads properly.
