### ISSUE TITLE
Learn You a Haskell fails to parse

### ISSUE THREAD

**Issue by szinn** [evan-buss/openbooks#55]
It appears the entry for the search results contains either unicode characters and also doesn't seem to contain author info. Perhaps rather than erroring out, a line could be displayed to retrieve the entry anyways?

**Comment by evan-buss** [comment]
This occurs because there are only 2 results for that query. Both of them are non-standard formats and fail to parse. In a recent update, I made it so that you can still download these via an alternate interface in the web UI. The issue is that the alternate interface only shows if at least 1 result was successfully parsed...

I will fix this and reference this issue when it is released. Thanks for the report!
