### ISSUE TITLE
Still reporting 4.3.0 on IRC Whois

### ISSUE THREAD

**Issue by AdrianSimionov** [evan-buss/openbooks#98]
IRC Whois is still reported as 4.3.0, although the software version changed.

**Comment by evan-buss** [comment]
That is by design, see the following [code comments](https://github.com/evan-buss/openbooks/blob/master/cmd/openbooks/main.go#L15-L21). 

The IRC admins require us to send the "WHOIS" response with the current version of the software. This allows them to whitelist / blacklist specific versions of OpenBooks.

Unless they contact me and tell me something is wrong (rate limiting broken / other server abuses), I will keep the IRC version the same even when the release version increments.

**Comment by AdrianSimionov** [comment]
This looks very much as an abuse to me.

While I do understand your statement around the success of the application, I still believe such a rule is more like a collar to make sure this tool can be controlled.
